### ISSUE TITLE
Problem in running the code

### ISSUE THREAD

**Issue by NanyangYe** [Senbon-Sakura/-1TnR_Structure#1]
Hi:

Can you specify how to run the code with parameters? I have the following error when running the code

python SparseNet_full_activate.py 1 1

Traceback (most recent call last):
  File "SparseNet_full_activate.py", line 135, in <module>
    circuit['VWL_w1_003'].dc_value=VSEL
IndexError: VWL_w1_003

**Comment by Senbon-Sakura** [comment]
> Hi:
> 
> Can you specify how to run the code with parameters? I have the following error when running the code
> 
> python SparseNet_full_activate.py 1 1
> 
> Traceback (most recent call last):
> File "SparseNet_full_activate.py", line 135, in
> circuit['VWL_w1_003'].dc_value=VSEL
> IndexError: VWL_w1_003

**Comment by Senbon-Sakura** [comment]
> Hi:
> 
> Can you specify how to run the code with parameters? I have the following error when running the code
> 
> python SparseNet_full_activate.py 1 1
> 
> Traceback (most recent call last):
> File "SparseNet_full_activate.py", line 135, in
> circuit['VWL_w1_003'].dc_value=VSEL
> IndexError: VWL_w1_003

Hi, lincolnBush:
    There is a bug in my code, in line 84 to 98, I initialized the WL, SL and BL voltage to zero,  so all of the cells in the array are deactivated. In line simulation phase, I select several cells to activate, 

`
#circuit['VWL_w1_000'].dc_value=VSEL
#circuit['VWL_w1_001'].dc_value=VSEL
#circuit['VWL_w1_002'].dc_value=VSEL
circuit['VWL_w1_003'].dc_value=VSEL
#circuit['VWL_w1_004'].dc_value=VSEL
circuit['VWL_w1_005'].dc_value=VSEL
#circuit['VWL_w1_006'].dc_value=VSEL
circuit['VWL_w1_007'].dc_value=VSEL

#circuit['VBL_w1_000'].dc_value=VSEL
#circuit['VBL_w1_001'].dc_value=VSEL
#circuit['VBL_w1_002'].dc_value=VSEL
circuit['VBL_w1_003'].dc_value=VSEL
#circuit['VBL_w1_004'].dc_value=VSEL
#circuit['VBL_w1_005'].dc_value=VSEL
#circuit['VBL_w1_006'].dc_value=VSEL
#circuit['VBL_w1_007'].dc_value=VSEL
`
you can find that I activate WL_003 in line 135 and BL_003 in line 144, but your input size of the array in 1, so you can try to run a larger array, such as "python SparseNet_full_activate.py 8 8"
